apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-cluster.secretName" . }}
  labels:
    app: {{ template "mysql-cluster.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ROOT_PASSWORD: {{ required ".rootPassword is missing" .Values.rootPassword | b64enc | quote }}
  USER: {{ required ".appUser is missing" .Values.appUser | b64enc | quote }}
  PASSWORD: {{ required ".appPassword is missing" .Values.appPassword | b64enc | quote }}
  DATABASE: {{ required ".appDatabase is missing" .Values.appDatabase | b64enc | quote }}
  DB_CONNECT_URL: {{ include "mysql-cluster.dbConnectURL" . | b64enc | quote }}
